
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";


export const GET_PROPERTY_DATA_SUCCESS = "GET_PROPERTY_DATA_SUCCESS";
export const GET_PROPERTY_DATA_REQUEST = "GET_PROPERTY_DATA_REQUEST";
export const GET_PROPERTY_DATA_FAILURE = "GET_PROPERTY_DATA_FAILURE";

export const GET_TENANTS_DATA_SUCCESS = "GET_TENANTS_DATA_SUCCESS";
export const GET_TENANTS_DATA_REQUEST = "GET_TENANTS_DATA_REQUEST";
export const GET_TENANTS_DATA_FAILURE = "GET_TENANTS_DATA_FAILURE";

export const GET_EXPENSES_DATA_SUCCESS = "GET_EXPENSES_DATA_SUCCESS";
export const GET_EXPENSES_DATA_REQUEST = "GET_EXPENSES_DATA_REQUEST";
export const GET_EXPENSES_DATA_FAILURE = "GET_EXPENSES_DATA_FAILURE";

export const GET_VACANT_PROPERTY_DATA_SUCCESS = "GET_VACANT_PROPERTY_DATA_SUCCESS";
export const GET_VACANT_PROPERTY_DATA_REQUEST = "GET_VACANT_PROPERTY_DATA_REQUEST";
export const GET_VACANT_PROPERTY_DATA_FAILURE = "GET_VACANT_PROPERTY_DATA_FAILURE";